In [9]:
import numpy as np
import sympy as sp
import itertools as iter
from tqdm import tqdm

n = 8
E = sp.symbols(f"e_:{n+1}")
Alpha = sp.symbols(f"alpha_:{n+1}")

positiveE7 = [
[0,-1,1,0,0,0,0,0],[1,1,1,1,0,0,0,0],[0,0,-1,1,0,0,0,0],
[0,0,0,-1,1,0,0,0],[0,0,0,0,-1,1,0,0],[0,0,0,0,0,-1,1,0],
[0,0,0,0,0,0,-1,1],[0,-1,0,1,0,0,0,0],[1,1,1,0,1,0,0,0],
[0,0,-1,0,1,0,0,0],[0,0,0,-1,0,1,0,0],[0,0,0,0,-1,0,1,0],
[0,0,0,0,0,-1,0,1],[0,-1,0,0,1,0,0,0],[1,1,0,1,1,0,0,0],
[1,1,1,0,0,1,0,0],[0,0,-1,0,0,1,0,0],[0,0,0,-1,0,0,1,0],
[0,0,0,0,-1,0,0,1],[1,0,1,1,1,0,0,0],[0,-1,0,0,0,1,0,0],
[1,1,0,1,0,1,0,0],[1,1,1,0,0,0,1,0],[0,0,-1,0,0,0,1,0],
[0,0,0,-1,0,0,0,1],[1,0,1,1,0,1,0,0],[0,-1,0,0,0,0,1,0],
[1,1,0,0,1,1,0,0],[1,1,0,1,0,0,1,0],[1,1,1,0,0,0,0,1],
[0,0,-1,0,0,0,0,1],[1,0,1,0,1,1,0,0],[1,0,1,1,0,0,1,0],
[0,-1,0,0,0,0,0,1],[1,1,0,0,1,0,1,0],[1,1,0,1,0,0,0,1],
[1,0,0,1,1,1,0,0],[1,0,1,0,1,0,1,0],[1,0,1,1,0,0,0,1],
[1,1,0,0,0,1,1,0],[1,1,0,0,1,0,0,1],[1,0,0,1,1,0,1,0],
[1,0,1,0,0,1,1,0],[1,0,1,0,1,0,0,1],[1,1,0,0,0,1,0,1],
[1,0,0,1,0,1,1,0],[1,0,0,1,1,0,0,1],[1,0,1,0,0,1,0,1],
[1,1,0,0,0,0,1,1],[1,0,0,0,1,1,1,0],[1,0,0,1,0,1,0,1],
[1,0,1,0,0,0,1,1],[2,1,1,1,1,1,1,0],[1,0,0,0,1,1,0,1],
[1,0,0,1,0,0,1,1],[2,1,1,1,1,1,0,1],[1,0,0,0,1,0,1,1],
[2,1,1,1,1,0,1,1],[1,0,0,0,0,1,1,1],[2,1,1,1,0,1,1,1],
[2,1,1,0,1,1,1,1],[2,1,0,1,1,1,1,1],[2,0,1,1,1,1,1,1]]

smplRoot = {
    Alpha[1]:E[2] - E[1],
    Alpha[2]:E[0] + E[1] + E[2] + E[3],
    Alpha[3]:E[3] - E[2],
    Alpha[4]:E[4] - E[3],
    Alpha[5]:E[5] - E[4],
    Alpha[6]:E[6] - E[5],
    Alpha[7]:E[7] - E[6],
    Alpha[8]:E[8] - E[7],
}

smplRoot_e = {
    Alpha[1]:np.array([0,-1,1,0,0,0,0,0]),
    Alpha[2]:np.array([1,1,1,1,0,0,0,0]),
    Alpha[3]:np.array([0,0,-1,1,0,0,0,0]),
    Alpha[4]:np.array([0,0,0,-1,1,0,0,0]),
    Alpha[5]:np.array([0,0,0,0,-1,1,0,0]),
    Alpha[6]:np.array([0,0,0,0,0,-1,1,0]),
    Alpha[7]:np.array([0,0,0,0,0,0,-1,1]),
    Alpha[8]:np.array([0,0,0,0,0,0,-1,1]),
}

def get_root(arr):
    root = np.array([0,0,0,0,0,0,0,0])
    for i in range(1,len(arr)):
        root += arr[i] * smplRoot_e[Alpha[i]]
    return list(root)

def get_root_alph(arr):
    root = 0
    for i in range(1,len(arr)):
        root += arr[i] * Alpha[i]
    return root

BASIS_alph = []
for i in tqdm(range(1)):
    for coef in positiveE7:
        BASIS_alph.append(get_root_alph(coef))


all_root = BASIS_alph + list(-np.array(BASIS_alph))

# representation like \sum a_i * e_i
def fun_e8(p,r,s,t,u,v,w,q):
    return p*smplRoot[Alpha[1]] + q*smplRoot[Alpha[2]] + r*smplRoot[Alpha[3]] +s*smplRoot[Alpha[4]] + t*smplRoot[Alpha[5]] + u*smplRoot[Alpha[6]] + v*smplRoot[Alpha[7]] + w*smplRoot[Alpha[8]],np.array([p,r,s,t,u,v,w,q])


# repesentation  like \sum a_i * \alpha_i
def fun_alpha(p,r,s,t,u,v,w,q):
    return p*Alpha[1] + r*Alpha[3] + s*Alpha[4] +t*Alpha[5] + u*Alpha[6] + v*Alpha[7] + q*Alpha[2],(p,r,s,t,u,v,w,q)

# projection vectors from E8 on E7
def projection(vector):
    _,coeff_E8 = fun_e8(2,4,6,5,4,3,2,3)
    _,coeff_E7 = fun_e8(2,4,6,5,4,3,0,3)
    n_i = (coeff_E8 - vector[1])
    n_i[-2] = 0
    print(n_i)
    print(coeff_E7 - 2*n_i)
    p,r,s,t,u,v,w,q = (coeff_E7 - 2*n_i)
    return fun_alpha(p,r,s,t,u,v,w,q)
# e_\lambda
orbit_1 = fun_e8(2,4,6,5,4,2,1,3)
# e_\mu
orbit_2 = fun_e8(2,3,4,3,2,2,1,2)
# e_\nu
orbit_3 = fun_e8(0,1,2,2,2,2,1,1)

print(len(set(all_root)))


100%|██████████| 1/1 [00:00<00:00, 242.73it/s]

126


In [10]:
weight_1, number1 = projection(orbit_1)
weight_2, number2 = projection(orbit_2)
weight_3, number2 = projection(orbit_3)


[0 0 0 0 0 1 0 0]
[2 4 6 5 4 1 0 3]
[0 1 2 2 2 1 0 1]
[2 2 2 1 0 1 0 1]
[2 3 4 3 2 1 0 2]
[-2 -2 -2 -1  0  1  0 -1]


In [11]:


# -x-y+z = mu => z = mu + (x+y)

def psi_w(x,y,weight):
    if weight + (x + y) in all_root:
        return weight + (x + y)
    else:
        return 0
    
def psi_table(weight):
    X,Y,Z = [],[],[]
    for i in tqdm(range(len(all_root))):
        x = all_root[i]
        for y in all_root:
            if psi_w(x,y,weight) in all_root:
                X.append(x)
                Y.append(y)
                Z.append(weight + x + y)
    return X,Y,Z


psi_1_arr = psi_table(weight_1)
psi_2_arr = psi_table(weight_2)
psi_3_arr = psi_table(weight_3)

X = list(set(psi_1_arr[0] + psi_2_arr[0] + psi_3_arr[0]))
Y = list(set(psi_1_arr[1] + psi_2_arr[1] + psi_3_arr[1]))
Z = list(set(psi_1_arr[2] + psi_2_arr[2] + psi_3_arr[2]))

# psi_1_xy = list(psi_1_arr.keys())
# psi_2_xy = list(psi_2_arr.keys())
# psi_3_xy = list(psi_2_arr.keys())

# all_xy = list(set(psi_1_xy + psi_2_xy))
# all_z = list(set(list(map(lambda pair:pair[0],all_xy)))) + list(set(list(map(lambda pair:pair[1],all_xy))))



100%|██████████| 126/126 [00:03<00:00, 37.82it/s]


In [12]:
# X

In [ ]:
f = open("summ_psi.txt","w")

def fun_cup(x,y,z,psi1,psi2):
    elem1 = psi1(psi2(x,y),z)
    elem2 = psi1(psi2(y,z),x)
    elem3 = psi1(psi2(z,x),y)
    sum = elem1 + elem2 + elem3
    if sum == 0:
        return 0
    for i in (sum % 2).args:
        if i % 2 == 0:
            return 0
    return sum

def psi_scobs(x,y,z,psi1,psi2):
    elem1 = fun_cup(x,y,z,psi1,psi2)
    elem2 = fun_cup(x,y,z,psi2,psi1)

    sum = elem1 + elem2
    return sum


for i in tqdm(range(len(Z))):
    z = Z[i]
    for x in X:
        for y in Y:
            result = 0
            result += psi_scobs(x,y,z,lambda x,y : psi_w(x,y,weight_1),lambda x,y : psi_w(x,y,weight_2))
            result += psi_scobs(x,y,z,lambda x,y : psi_w(x,y,weight_1),lambda x,y : psi_w(x,y,weight_3))
            result += psi_scobs(x,y,z,lambda x,y : psi_w(x,y,weight_2),lambda x,y : psi_w(x,y,weight_3))

            if (result != 0):
                print(result)
                print(x)
                print(y)
                print(z)

100%|██████████| 49/49 [06:58<00:00,  8.54s/it]
